import os
import uuid
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from models.questionnaire import AssessmentResult, RiskLevel


# ── Brand Colours ──────────────────────────────────────────────────────────────
BRAND_DARK   = colors.HexColor("#0D1B2A")   # Navy
BRAND_ACCENT = colors.HexColor("#00C2CB")   # Cyan
BRAND_LIGHT  = colors.HexColor("#F0F4F8")   # Light grey
RED          = colors.HexColor("#E63946")
AMBER        = colors.HexColor("#F4A261")
GREEN        = colors.HexColor("#2A9D8F")
WHITE        = colors.white

RISK_COLOURS = {
    RiskLevel.LOW:      GREEN,
    RiskLevel.MEDIUM:   AMBER,
    RiskLevel.HIGH:     colors.HexColor("#E76F51"),
    RiskLevel.CRITICAL: RED,
}


class ReportGenerator:
    """Generates branded PDF compliance gap reports."""

    OUTPUT_DIR = os.getenv("REPORT_OUTPUT_DIR", "reports")

    def __init__(self):
        os.makedirs(self.OUTPUT_DIR, exist_ok=True)

    def generate(self, result: AssessmentResult) -> str:
        """Generate a PDF report and return the file path."""
        filename  = f"{self.OUTPUT_DIR}/cyberguard_{uuid.uuid4().hex[:8]}.pdf"
        doc       = SimpleDocTemplate(
            filename,
            pagesize    = A4,
            topMargin   = 1.5 * cm,
            bottomMargin= 1.5 * cm,
            leftMargin  = 2 * cm,
            rightMargin = 2 * cm,
        )
        styles  = self._build_styles()
        story   = []

        # Cover
        story += self._cover(result, styles)
        story.append(PageBreak())

        # Executive Summary
        story += self._executive_summary(result, styles)
        story.append(Spacer(1, 0.5 * cm))

        # Score Dashboard
        story += self._score_dashboard(result, styles)
        story.append(Spacer(1, 0.5 * cm))

        # Top Priorities
        story += self._top_priorities(result, styles)
        story.append(PageBreak())

        # Detailed Control Results
        for ctrl in result.controls:
            story += self._control_section(ctrl, styles)
            story.append(Spacer(1, 0.4 * cm))

        # Footer note
        story.append(Spacer(1, 1 * cm))
        story.append(Paragraph(
            "This report was generated by CyberGuard AI Compliance Platform. "
            "All recommendations are aligned with NCSC Cyber Essentials requirements. "
            "© CyberGuard — ashcybersec.co.uk",
            styles["footer"]
        ))

        doc.build(story)
        return filename

    # ── Section Builders ───────────────────────────────────────────────────────

    def _cover(self, result: AssessmentResult, styles: dict) -> list:
        risk_colour = RISK_COLOURS[result.overall_risk]
        elements = [
            Spacer(1, 2 * cm),
            Paragraph("CyberGuard", styles["brand"]),
            Paragraph("AI Compliance Platform", styles["brand_sub"]),
            HRFlowable(width="100%", thickness=2, color=BRAND_ACCENT, spaceAfter=20),
            Spacer(1, 1 * cm),
            Paragraph("Cyber Essentials Gap Analysis Report", styles["title"]),
            Spacer(1, 0.5 * cm),
            Paragraph(result.client.company_name, styles["company_name"]),
            Spacer(1, 0.3 * cm),
            Paragraph(f"Prepared for: {result.client.contact_name}", styles["subtitle"]),
            Paragraph(f"Date: {datetime.now().strftime('%d %B %Y')}", styles["subtitle"]),
            Paragraph(f"Industry: {result.client.industry}", styles["subtitle"]),
            Spacer(1, 1.5 * cm),
            # Overall risk badge
            Table(
                [[
                    Paragraph("OVERALL RISK", styles["badge_label"]),
                    Paragraph(result.overall_risk.value.upper(), styles["badge_value"]),
                    Paragraph(f"{result.overall_score}/100", styles["badge_score"]),
                ]],
                colWidths=[5 * cm, 5 * cm, 5 * cm],
                style=TableStyle([
                    ("BACKGROUND", (0, 0), (-1, -1), risk_colour),
                    ("TEXTCOLOR",  (0, 0), (-1, -1), WHITE),
                    ("ALIGN",      (0, 0), (-1, -1), "CENTER"),
                    ("VALIGN",     (0, 0), (-1, -1), "MIDDLE"),
                    ("ROWHEIGHT",  (0, 0), (-1, -1), 1.5 * cm),
                    ("ROUNDEDCORNERS", [8]),
                ])
            ),
            Spacer(1, 0.5 * cm),
            Paragraph(
                "✅ Cyber Essentials Ready" if result.cyber_essentials_ready
                else "❌ Not Yet Cyber Essentials Ready",
                styles["ce_status_pass" if result.cyber_essentials_ready else "ce_status_fail"]
            ),
        ]
        return elements

    def _executive_summary(self, result: AssessmentResult, styles: dict) -> list:
        return [
            Paragraph("Executive Summary", styles["section_heading"]),
            HRFlowable(width="100%", thickness=1, color=BRAND_ACCENT, spaceAfter=8),
            Paragraph(result.executive_summary, styles["body"]),
        ]

    def _score_dashboard(self, result: AssessmentResult, styles: dict) -> list:
        elements = [Paragraph("Control Scores", styles["section_heading"]),
                    HRFlowable(width="100%", thickness=1, color=BRAND_ACCENT, spaceAfter=8)]

        table_data = [["Control", "Score", "Risk Level", "Passed"]]
        for ctrl in result.controls:
            rc = RISK_COLOURS[ctrl.risk_level]
            table_data.append([
                ctrl.control_name,
                f"{ctrl.score}/100",
                ctrl.risk_level.value.upper(),
                f"{ctrl.passed_checks}/{ctrl.total_checks}"
            ])

        tbl = Table(table_data, colWidths=[7 * cm, 3 * cm, 4 * cm, 3 * cm])
        style = TableStyle([
            ("BACKGROUND",  (0, 0), (-1, 0),  BRAND_DARK),
            ("TEXTCOLOR",   (0, 0), (-1, 0),  WHITE),
            ("FONTNAME",    (0, 0), (-1, 0),  "Helvetica-Bold"),
            ("FONTSIZE",    (0, 0), (-1, -1), 9),
            ("ALIGN",       (1, 0), (-1, -1), "CENTER"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [BRAND_LIGHT, WHITE]),
            ("GRID",        (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("VALIGN",      (0, 0), (-1, -1), "MIDDLE"),
            ("ROWHEIGHT",   (0, 0), (-1, -1), 0.8 * cm),
        ])
        # Colour-code risk column per row
        for i, ctrl in enumerate(result.controls, start=1):
            style.add("TEXTCOLOR", (2, i), (2, i), RISK_COLOURS[ctrl.risk_level])
            style.add("FONTNAME",  (2, i), (2, i), "Helvetica-Bold")

        tbl.setStyle(style)
        elements.append(tbl)
        return elements

    def _top_priorities(self, result: AssessmentResult, styles: dict) -> list:
        elements = [
            Spacer(1, 0.3 * cm),
            Paragraph("Top Remediation Priorities", styles["section_heading"]),
            HRFlowable(width="100%", thickness=1, color=BRAND_ACCENT, spaceAfter=8),
            Paragraph(f"Estimated effort: {result.estimated_effort}", styles["italic"]),
            Spacer(1, 0.2 * cm),
        ]
        for i, p in enumerate(result.top_priorities, 1):
            elements.append(Paragraph(f"{i}. {p}", styles["priority_item"]))
        return elements

    def _control_section(self, ctrl, styles: dict) -> list:
        rc = RISK_COLOURS[ctrl.risk_level]
        elements = [
            Paragraph(ctrl.control_name, styles["control_heading"]),
            Paragraph(ctrl.summary, styles["body"]),
            Spacer(1, 0.2 * cm),
        ]
        if not ctrl.gaps:
            elements.append(Paragraph("✅ No gaps identified for this control.", styles["pass_note"]))
        else:
            for gap in sorted(ctrl.gaps, key=lambda g: g.priority):
                priority_label = ["", "CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"][gap.priority]
                elements.append(Paragraph(
                    f"[P{gap.priority} – {priority_label}] {gap.gap_title}",
                    styles["gap_title"]
                ))
                elements.append(Paragraph(gap.description, styles["body"]))
                for step in gap.remediation_steps:
                    elements.append(Paragraph(f"→ {step}", styles["remediation_step"]))
                if gap.ncsc_reference:
                    elements.append(Paragraph(f"NCSC Ref: {gap.ncsc_reference}", styles["italic"]))
                elements.append(Spacer(1, 0.2 * cm))
        return elements

    # ── Style Definitions ──────────────────────────────────────────────────────

    def _build_styles(self) -> dict:
        base = getSampleStyleSheet()
        def S(name, **kwargs):
            return ParagraphStyle(name, **kwargs)

        return {
            "brand":         S("brand",         fontSize=28, textColor=BRAND_DARK,   fontName="Helvetica-Bold", alignment=TA_CENTER),
            "brand_sub":     S("brand_sub",      fontSize=12, textColor=BRAND_ACCENT, fontName="Helvetica",      alignment=TA_CENTER, spaceAfter=6),
            "title":         S("title",          fontSize=20, textColor=BRAND_DARK,   fontName="Helvetica-Bold", alignment=TA_CENTER, spaceAfter=10),
            "company_name":  S("company_name",   fontSize=16, textColor=BRAND_ACCENT, fontName="Helvetica-Bold", alignment=TA_CENTER, spaceAfter=4),
            "subtitle":      S("subtitle",       fontSize=10, textColor=colors.grey,  fontName="Helvetica",      alignment=TA_CENTER, spaceAfter=2),
            "section_heading": S("sh",           fontSize=13, textColor=BRAND_DARK,   fontName="Helvetica-Bold", spaceBefore=10, spaceAfter=4),
            "control_heading": S("ch",           fontSize=11, textColor=WHITE,        fontName="Helvetica-Bold", backColor=BRAND_DARK, spaceBefore=8, spaceAfter=4, leftIndent=4, rightIndent=4),
            "gap_title":     S("gap_title",      fontSize=10, textColor=BRAND_DARK,   fontName="Helvetica-Bold", spaceBefore=6, spaceAfter=2),
            "body":          S("body",           fontSize=9,  textColor=colors.black, fontName="Helvetica",      spaceAfter=3, leading=13),
            "italic":        S("italic",         fontSize=9,  textColor=colors.grey,  fontName="Helvetica-Oblique", spaceAfter=4),
            "remediation_step": S("rs",          fontSize=9,  textColor=BRAND_DARK,   fontName="Helvetica",      leftIndent=12, spaceAfter=2),
            "priority_item": S("pi",             fontSize=10, textColor=BRAND_DARK,   fontName="Helvetica",      leftIndent=8, spaceAfter=4),
            "pass_note":     S("pass_note",      fontSize=9,  textColor=GREEN,        fontName="Helvetica-Bold", spaceAfter=4),
            "badge_label":   S("bl",             fontSize=9,  textColor=WHITE,        fontName="Helvetica-Bold", alignment=TA_CENTER),
            "badge_value":   S("bv",             fontSize=14, textColor=WHITE,        fontName="Helvetica-Bold", alignment=TA_CENTER),
            "badge_score":   S("bs",             fontSize=12, textColor=WHITE,        fontName="Helvetica",      alignment=TA_CENTER),
            "ce_status_pass": S("csp",           fontSize=12, textColor=GREEN,        fontName="Helvetica-Bold", alignment=TA_CENTER),
            "ce_status_fail": S("csf",           fontSize=12, textColor=RED,          fontName="Helvetica-Bold", alignment=TA_CENTER),
            "footer":        S("footer",         fontSize=7,  textColor=colors.grey,  fontName="Helvetica",      alignment=TA_CENTER),
        }
